### ISSUE TITLE
switch remaining / actual timecode

### ISSUE THREAD

**Issue by Jonathan1718** [chabad360/resolume-timecode#4]
Is it possible to add a tick in advanced settings to switch between remaining time and elapsed time ? Awesome work btw.

**Comment by chabad360** [comment]
It's a bit complicated for two reasons:
A. That whole calculation happens on the server, and is sent to the client as text, so inverting it on the client is a bit complicated.
B. I could theoretically move that but of the calculation to the client, but considering JS's issues with floating point processing (which were a legitimate issue when I did the whole calculation there) I don't think that's a good idea.

I'll see if I can come up with a good way to do it, but I'm not really sure there is one...

Additionally, could you describe the use case? I personally don't really see why that would be useful if you can't see how long the whole clip is (which my interface doesn't really allow for).

**Comment by Jonathan1718** [comment]
Hi ,So maybe put a switch on the server side . It would be a better solution if the elapsed timecode is sent to the clients. The less the client do the better …I use resolume as media player in timecode synchronized shows and I often have the demand to show the timecode of the video playing so cues can be given to dancers and actors…Actually I use a multitrack audio player that control resolume trough SMPTE timecode , I have a small server that grab this timecode and convert it into OSC and send it to touch osc app on phone and tablets. As I know do smaller shows (COVID… ) I have less budget so no multitrack player and no SMPTE timecodeYour solution is pretty neat as it avoid me to use SMPTE , having  the small timecode converter (which is a computer) and having touch osc app installed on reading devices.  Jonathan

**Comment by chabad360** [comment]
I see.

Yes, perhaps just adding a switch server side is the way to go.

I'll add it to the next feature wave.

**Comment by Jonathan1718** [comment]
Thanks it would be awesome ! Jonathan
